Add Pov-3d viewer
polyground/pov-3d pull request #1
Opened 2024-03-18 10:34 UTC by JOHNKIM-KK

## Description

- Project initial setting
- Create Viewer
- Add Preset (Viewer Options)
- Add Example

<br/>

## Motivation and Context

**Project initial setting**
- create vite
- Configure package.json

**Viewer**
- 3D Model Visualization: With a 3D viewer, you can visually represent a 3D model. It shows the shape and structure of the model, allowing you to examine it in detail through operations such as rotation, zooming, and panning.
- Camera Control: A 3D viewer allows you to manipulate the camera to view the model from various angles. You can rotate or move the camera to adjust the view of the model according to your preference.
- Lighting and Material Settings: A 3D viewer may offer the ability to adjust the lighting and material of the model. You can modify the lighting to add lighting effects to the model or change the material to alter the surface properties of the model.
- Animation Playback: Some 3D viewers can play animations included in the model. You can visually observe the movements and changes of the model through animation playback.

**Preset**
- "Preset" is created to allow users to select options that are suitable for their 3D models.

**Example**
1. Import the POV-3D library into your project.

2. Create a container element in your HTML file where the viewer will be displayed.

3. Instantiate a new POV-3D viewer object.
4. Set the container element as the target for the viewer.
5. Load a 3D model file using the viewer's load() method.
6. Optionally, 
    If you pass a DOM HTMLElement as the first argument to the viewer class, the viewer will be appended to that DOM     
   element, allowing you to display the viewer at the desired location.
   If you pass a preset that you have predefined as the second argument, you can use the viewer with options that are 
   specific to that preset.
Alternatively, if you pass a ViewerOptions object as the second argument, you can individually modify the properties according to the ViewerOptions to customize the viewer.
Update and re-render the model as needed based on user interactions or changes to the model data.

<br/>

## Types of Changes

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2024-03-21 03:19 UTC, jack-kdl requested changes
우리는 다양성을 가지는 솔루션을 제공하고자 함으로 사용성과 일관성을 조금더 잡고 가시죠

2024-03-21 03:19 UTC, jack-kdl commented on examples/viewer_example_in_html/example.html
vanila js example이군요. 명확하게 example_javascript.html 은 어떨까요?

2024-03-21 03:19 UTC, jack-kdl commented on examples/viewer_example_in_html/example.html
> +      <div class="my_viewer"></div>
example인 만큼 명확하게 id로 delegation 하는건 어떨까요?

2024-03-21 03:19 UTC, jack-kdl commented on src/viewer.js
> +class Viewer {
클래스 이름이 좀 너무 제너럴 하지 않나요?

2024-03-21 03:19 UTC, jack-kdl commented on examples/viewer_example_in_html/example.html
> +      import Viewer from "../../build/viewer";
요방법은 제너럴 한건가요? 브라우저 호환성이 떨어질꺼 같은데?

<script src="https://.../pov-3d.js"></script>
요 방법이 좀더 제너럴하고 브라우저 호환성도 지킬수있지 않나요?

2024-03-21 03:19 UTC, jack-kdl commented on examples/viewer_example_in_html/example.html
> +      });
개발자들이 DOMContentLoaded 이벤트를 알아야할까요?

pov_3d_viewer('#my_viewer', (viewer) => {
    viewer.load('....');
});
이런형태는 어떨까요?

pov_3d_viewer('.my_viewer', ...);
pov_3d_viewer(document.querySelector(".my_viewer"), ...);

이렇게 사용자에게 다양성을 주는것도 좋을듯하고요.

2024-03-21 03:19 UTC, jack-kdl commented on examples/viewer_example_in_js/example.js
위에 example.html 하고 뭐가 다르죠?

2024-03-21 03:19 UTC, jack-kdl commented on src/viewer.js
> +const DRACO_LOADER = new DRACOLoader(MANAGER).setDecoderPath(
잉? main module에서 example을 reference?

2024-03-21 03:19 UTC, jack-kdl commented on styles.css
이파일 용도는 뭔데 여기 위치하나요?

2024-03-22 04:19 UTC, JOHNKIM-KK commented on src/viewer.js
> +const DRACO_LOADER = new DRACOLoader(MANAGER).setDecoderPath(
three 의 example을 경로를 의미합니다!
저희 Pov-3d의 example는 reference하지 않았습니다!

2024-03-22 04:20 UTC, JOHNKIM-KK commented on styles.css
프로젝트 초기세팅시 있던 style.css입니다.
현재 사용하고 있지 않아서 제거 하였습니다.

2024-04-03 02:56 UTC, kimswon requested changes

2024-04-03 02:56 UTC, kimswon commented on src/pov_3d_viewer.js
> +import { OBJLoader } from "three/examples/jsm/loaders/OBJLoader.js";
do not import just example, import logic

2024-04-03 02:56 UTC, kimswon commented on src/pov_3d_viewer.js
> +const DRACO_LOADER = new DRACOLoader(MANAGER).setDecoderPath(
treejs treat loader as a adopter, inherit addon mechanism on our solution

2024-04-03 02:56 UTC, kimswon commented on src/pov_3d_viewer.js
> +  async load(file) {
make it as loader system

2024-04-04 08:31 UTC, merged